name: Bug Report
description: Let us know about an unexpected error, a crash, or an incorrect behavior.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        # Thank you for opening an issue.

        ## Filing a bug report

        To fix problems, we need clear reproduction cases - we need to be able to see it happen locally. A reproduction case is ideally something an engineer can git-clone or copy-paste and run immediately, without inventing any details or context.

        * A short example can be directly copy-pasteable; longer examples should be in separate git repositories, especially if multiple files are needed
        * Please include all needed context. For example, if you figured out that an expression can cause a crash, put the expression in a variable definition or a resource
        * Set defaults on (or omit) any variables. The person reproducing it should not need to invent variable settings
        * If multiple steps are required, consider scripting it in a simple shell script. Providing a script can be easier than explaining what changes to make to the config between runs.
        * Omit any unneeded complexity: remove variables, conditional statements, functions, modules, providers, and resources that are not needed to trigger the bug

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a description of the bug
      placeholder: Provide a description of the bug
      value:
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: What should have happened?
      value:
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: What actually happened?
      value:
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to Reproduce
      description: |
        Please list the full steps required to reproduce the issue
      placeholder: Steps to reproduce
      value:
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: Version
      description: If you are not running the latest version, please try upgrading because your issue may have already been fixed.
      render: shell
      placeholder: ...software version...
      value:
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Paste the relevant parts of your configuration between the ``` marks below. For configs larger than a few resources, or that involve multiple files, please make a GitHub repository that we can clone, rather than copy-pasting multiple files in here.
      placeholder: ...configuration files...
      value: 
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Place the logs of your issue here.
      placeholder: ...logs...
      value: 
    validations:
      required: true

  - type: textarea
    id: add-context
    attributes:
      label: Additional Context
      description: |
        Are there anything atypical about your situation that we should know?
      placeholder: Additional context...
      value:
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        **Note:** If the submit button is disabled and you have filled out all required fields, please check that you did not forget a **Title** for the issue.
