name: Feature Request
description: Suggest a new feature or other enhancement.
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        # Thank you for opening a feature request.

  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: |
          If you have an idea for a new functionality or an improvement to this project, please describe it below.
          In this section, it's helpful to include specific examples of how what you are suggesting might look in configuration files, or on the command line, since that allows us to understand the full picture of what you are proposing.
          If you're not sure of some details, don't worry! When we evaluate the feature request we may suggest modifications as necessary to work within the design constraints of this project.
      placeholder:
      value:
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Cases
      description: |
        In order to properly evaluate a feature request, it is necessary to understand the use cases for it.
        Please describe below the _end goal_ you are trying to achieve that has led you to request this feature.
        Please keep this section focused on the problem and not on the suggested solution. We'll get to that in a moment, below!
      placeholder:
      value:
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **Note:** If the submit button is disabled and you have filled out all required fields, please check that you did not forget a **Title** for the issue.
